// Generates src/text/fontMetrics.ts from KaTeX's font metric tables, which
// are derived from the Computer Modern fonts. Run after upgrading KaTeX:
//   node scripts/gen-font-metrics.ts
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const root = join(import.meta.dirname, "..");
const source = join(root, "node_modules", "katex", "src", "fontMetricsData.js");
// The file isn't in KaTeX's package exports, so import it by path.
const data = (await import(pathToFileURL(source).href)).default as Record<string, Record<string, number[]>>;

const FONTS = [
  "Main-Regular",
  "Main-Bold",
  "Main-Italic",
  "Main-BoldItalic",
  "SansSerif-Regular",
  "SansSerif-Bold",
  "SansSerif-Italic",
  "Typewriter-Regular",
];

const out: Record<string, Record<number, [number, number, number]>> = {};
for (const font of FONTS) {
  const table = data[font];
  if (!table) throw new Error(`KaTeX has no metrics for ${font}`);
  const entries: Record<number, [number, number, number]> = {};
  for (const [code, m] of Object.entries(table)) {
    // [depth, height, italic, skew, width] in em.
    const [depth, height, , , width] = m as [number, number, number, number, number];
    entries[Number(code)] = [round(height), round(depth), round(width)];
  }
  out[font] = entries;
}

function round(v: number) {
  return Math.round(v * 100000) / 100000;
}

const header = `// GENERATED by scripts/gen-font-metrics.ts from KaTeX's fontMetricsData.js.
// Do not edit. KaTeX is MIT-licensed (Copyright (c) 2013-2020 Khan Academy and
// other contributors); the metrics come from the Computer Modern fonts.
//
// For each font: character code -> [height, depth, width], in em.
`;
const body = `export const FONT_METRICS: Record<string, Record<number, readonly [number, number, number]>> = ${JSON.stringify(out)};\n`;
writeFileSync(join(root, "src", "text", "fontMetrics.ts"), header + body);
console.log(`Wrote src/text/fontMetrics.ts (${FONTS.length} fonts, ${(body.length / 1024).toFixed(0)} KB)`);
